### ISSUE TITLE
repo submission task list

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/blockstrap#5]
We need to secure the slug, so need to submit even a basic version of the theme first.

- [x] readme.txt need updated.
- [x] replace textdomain in composer packages.
- [x] add a warning if AUI or SD older version loaded.
- [x] screenshot should be 4:3 (ideally 1200x900)
